<?php
if (!defined('ABSPATH')) {
    define('ABSPATH', $_SERVER['DOCUMENT_ROOT'] . '/');
}


require_once( ABSPATH . 'an_config.php' );

/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.4 setup script
 * Date: Wed, 13 Sep 2017 18:13:11 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: main [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'home';
$cfg['Servers'][$i]['host'] = '172.17.0.1';
$cfg['Servers'][$i]['port'] = 3307;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = DB_USER_AN;
$cfg['Servers'][$i]['password'] = DB_PASSWORD_AN;



/* End of servers configuration */

$cfg['blowfish_secret'] = '!P^0A$;!\\#z5@K0W+k&?"=5o&Nw3-<j3';
$cfg['DefaultLang'] = 'ru';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
